export const ODIA_CHARACTER_BY_LABEL: Record<string, string> = {
	VOW_A: "ଅ",
	VOW_AA: "ଆ",
	VOW_I: "ଇ",
	VOW_II: "ଈ",
	VOW_U: "ଉ",
	VOW_UU: "ଊ",
	VOW_RU: "ଋ",
	VOW_E: "ଏ",
	VOW_AI: "ଐ",
	VOW_O: "ଓ",
	VOW_AU: "ଔ",
	CONS_KA: "କ",
	CONS_KHA: "ଖ",
	CONS_GA: "ଗ",
	CONS_GHA: "ଘ",
	CONS_NGA: "ଙ",
	CONS_CA: "ଚ",
	CONS_CHA: "ଛ",
	CONS_JA: "ଜ",
	CONS_JHA: "ଝ",
	CONS_NYA: "ଞ",
	CONS_TTA: "ଟ",
	CONS_TTHA: "ଠ",
	CONS_DDA: "ଡ",
	CONS_DDHA: "ଢ",
	CONS_NNA: "ଣ",
	CONS_TA: "ତ",
	CONS_THA: "ଥ",
	CONS_DA: "ଦ",
	CONS_DHA: "ଧ",
	CONS_NA: "ନ",
	CONS_PA: "ପ",
	CONS_PHA: "ଫ",
	CONS_BA: "ବ",
	CONS_BHA: "ଭ",
	CONS_MA: "ମ",
	CONS_YA: "ଯ",
	CONS_RA: "ର",
	CONS_LLA: "ଳ",
	CONS_LA: "ଲ",
	CONS_SHA: "ଶ",
	CONS_SSHA: "ଷ",
	CONS_SA: "ସ",
	CONS_HA: "ହ",
	CONS_YYA: "ୟ",
	DIGIT_0: "୦",
	DIGIT_1: "୧",
	DIGIT_2: "୨",
	DIGIT_3: "୩",
	DIGIT_4: "୪",
	DIGIT_5: "୫",
	DIGIT_6: "୬",
	DIGIT_7: "୭",
	DIGIT_8: "୮",
	DIGIT_9: "୯",
};

export function getOdiaCharacter(label: string): string {
	return ODIA_CHARACTER_BY_LABEL[label] ?? label;
}
